### ISSUE TITLE
not asking for app password

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#186]
This Bug is like Issue#150
If you go to "export your account" and you can see your details (it doesn't matter if with or without the private key). Then, if you close the app and open it again it asks you for the app password (no touchID funktion). With the correct password you are in the app again but if you close the app again and reopen it then it does NOT ask you for the password and you can do it again and again without the app 
password.
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

![photo-2016-04-04-18-13-51_1382](https://cloud.githubusercontent.com/assets/17567386/14254882/f8e87396-fa91-11e5-9427-85df82019eed.PNG)

**Comment by jabo38** [comment]
Confirmed.  

There are two issues here. 

1. Touch ID doesn't come up. 

2. After repeated opening and closing the account on the export account panel eventually enter password doesn't even come up.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by Espo02** [comment]
The Bug is still alive in build 34.
I you want to export the account and it asks you for the a password. <-- on this site of the app is a bug. You can close the app and reopen it. The App it asks for the appPassword (and now it works with TouchID since this version) and if it's right, ok. Then, if you close the app a second time and reopen it, it asks NOT for a appPassword. Thats the Bug.

**Comment by jabo38** [comment]
Transaction hash: 17993d6fc07ad13af022ff1523a079444bc2401070eb6e045b1a8594fcd1959d
Bounty paid.

**Comment by Espo02** [comment]
In Version 2.0 Beta 36 the Bug is still existing.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by Espo02** [comment]
seems to work very well :+1:
