### ISSUE TITLE
Scanning QRs produced on Android app doesn't show correct balance

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#20]
This QR for Android was for 2000 XEM, not 2000000000 as shown on my phone.  There was a no decimal point included which was a bug.  

![photo_2015-10-30_08-32-11](https://cloud.githubusercontent.com/assets/10395907/10834992/912cc08a-7ee1-11e5-91ec-a38922949689.jpg)
![photo_2015-10-30_08-38-31](https://cloud.githubusercontent.com/assets/10395907/10835005/9e770ee4-7ee1-11e5-9668-4f2b5d849a3e.jpg)

**Comment by jabo38** [comment]
Also, when I lowered the amount of the transaction, the fee did not auto update to a lower fee, it just stayed 157.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by jabo38** [comment]
when scanning old android invoices, the problem persists.  would like to check on a new version of android app when it come out.

**Comment by LyubomirDominik** [comment]
I will check this but it should work

**Comment by jabo38** [comment]
So for instance the QR at the top of this page is a QR that I am 90% positive was made by an Android phone a long time ago.  I don't know if those QRs from a long time ago are still valid or not, but when I scan it, the balance is wrong.  Unless I have a working Android app, I am only limited to testing old QRs.  When the next Android app is released that works, I can tell you for sure.

**Comment by jabo38** [comment]
Doesn't work

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
