### ISSUE TITLE
Choose account oppens multitimes

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#237]
The "choose Multisig Account" Button pops multitimes open.
If you tap 3 times on Account [1] you have to choose the account 3 times [2].
![photo-2016-06-11-22-06-51_2197](https://cloud.githubusercontent.com/assets/17567386/15987220/4ef1b0f8-3021-11e6-816c-1cea8aa82f22.PNG)
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 38

**Comment by jabo38** [comment]
@LyubomirDominik I am on Version 2 Build 38 and it isn't fixed.

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash: cc5e5c65b0202c72b643208e54a9f0d3b009b9cadd218b03400fedda79f88706
