### ISSUE TITLE
signing multisig transaction for activating delegated harvesting is blank

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#241]
phone notifies me to look at a transaction that needs to be signed (activating delegated harvesting on a multisig account) but when I go to sign the transaction the panel is blank.  

![image](https://cloud.githubusercontent.com/assets/10395907/15991731/a611ea44-30f6-11e6-95a2-1554b8ff5eec.png)

**Comment by Espo02** [comment]
Yes, I could reproduce it.
![photo-2016-06-13-11-40-19_2208](https://cloud.githubusercontent.com/assets/17567386/16003217/d89e1f40-315b-11e6-86e4-1cae3edecfe4.PNG)

**Comment by LyubomirDominik** [comment]
Fixed in Verson 2 Build 39

**Comment by Espo02** [comment]
sorry, but on my phone it's still blank
![photo-2016-06-14-21-08-56_2227](https://cloud.githubusercontent.com/assets/17567386/16056182/a5db4000-3274-11e6-99a5-d1b10f08a2ea.PNG)
![photo-2016-06-14-21-08-47_2226](https://cloud.githubusercontent.com/assets/17567386/16056186/a6f4caa6-3274-11e6-8527-88f1f072e72c.PNG)

**Comment by jabo38** [comment]
This issue is still a bug.  This is what happens to be clear.  

There are parent accounts that are signers, and a child account that has been turned into a multisig account.  

One of the parent accounts activates delegated harvesting on the chlid account.  I log into the child account and there is a message for me to sign a transaction (The child account should never get messages for any reason to sign any transaction because it can't ever sign anyway.)  The I go to sign and the screen is blank.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by jabo38** [comment]
Was the fix to remove the ability to sign at all?  Now I don't even get a blank screen.

**Comment by LyubomirDominik** [comment]
Yes, as issue was that that blank appears. Mobile apps do not support such functionality.
