### ISSUE TITLE
Confugurations -> Configurations 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#45]
The title of the Configurations panel is not spelled correctly.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 build 9

**Comment by jabo38** [comment]
hmmm, I am on 2.9 and still see it.  Maybe on the next release?

**Comment by LyubomirDominik** [comment]
sorry my bad I fix it in wrong localization file) 

Fixed in Version 2 (10)

**Comment by jabo38** [comment]
fixed
